# Generated by Django 2.1 on 2018-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, unique=True)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
